### ISSUE TITLE
Workflow stopped after authentication

### ISSUE THREAD

**Issue by tianminzheng** [run-llama/multi-agent-concierge#10]
For the workflow.py, after I completed the authentication, I found that the process stopped, and other agents did not continue to operate further.
The interaction log is as follows:

Authentication Agent is complete
You have been successfully authenticated. If you need any further assistance, please let me know!
Step authenticate produced no event
Step account_balance produced no event

Then，workflow stopped.

**Comment by logan-markewich** [comment]
With recent refactors, going to close this for now. Thanks!
