### ISSUE TITLE
Example Not Runnable

### ISSUE THREAD

**Issue by brycecf** [run-llama/multi-agent-concierge#4]
The following line causes an error: https://github.com/run-llama/multi-agent-concierge/blob/f1a0e414092b15c664148263f02e64e164f8071c/workflows.py#L84

```
ParamValidationError: Parameter validation failed:
Invalid length for parameter toolConfig.tools, value: 0, valid min length: 1
```

* `llama-index-core`==0.10.66

**Comment by logan-markewich** [comment]
With recent refactors, going to close this for now. Thanks!
