### ISSUE TITLE
Field Required ConciergeEvent

### ISSUE THREAD

**Issue by MotivaoCrypto** [run-llama/multi-agent-concierge#8]
I only run the workflow.py and immediately get this error. It comes from the return initialize()

pydantic_core._pydantic_core.ValidationError: 3 validation errors for ConciergeEvent
request
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
just_completed
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
need_help
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

**Comment by logan-markewich** [comment]
With recent refactors, going to close this for now. Thanks!
